project:
  type: website

website:
  title: "Chicago Bulls 2022-2023 Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - players.qmd
      - models.qmd
      - about.qmd
      - sources.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



